openapi: 3.0.1
info:
  title: EmpaMind API
  version: 1.0.0
  description: API Gateway for EmpaMind mental wellness companion

paths:
  /chats:
    get:
      summary: List all chat sessions
      operationId: listChats
      security:
        - CognitoAuthorizer: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  chats:
                    type: array
                    items:
                      type: object
                      properties:
                        chatId:
                          type: string
                        title:
                          type: string
                        lastMessageTime:
                          type: string
                        createdAt:
                          type: string
        '500':
          description: Internal server error
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: ${list_chats_invoke_arn}
        passthroughBehavior: when_no_match
        contentHandling: CONVERT_TO_TEXT
    options:
      summary: CORS preflight
      operationId: optionsChats
      responses:
        '200':
          description: CORS response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: '{"statusCode": 200}'
        responses:
          default:
            statusCode: 200
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization'"

  /chat:
    post:
      summary: Send a chat message
      operationId: postChat
      security:
        - CognitoAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                chatId:
                  type: string
                  description: Optional. If not provided, creates a new chat
                title:
                  type: string
                  description: Optional. Title for new chat (defaults to first message)
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  sentiment:
                    type: string
                  chatId:
                    type: string
        '400':
          description: Bad request
        '500':
          description: Internal server error
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: ${send_message_invoke_arn}
        passthroughBehavior: when_no_match
        contentHandling: CONVERT_TO_TEXT
    options:
      summary: CORS preflight
      operationId: optionsChat
      responses:
        '200':
          description: CORS response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: '{"statusCode": 200}'
        responses:
          default:
            statusCode: 200
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization'"

  /chat/voice:
    post:
      summary: Send a voice chat message
      operationId: postVoiceChat
      security:
        - CognitoAuthorizer: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - audio
              properties:
                audio:
                  type: string
                  description: Base64-encoded audio file
                audioFormat:
                  type: string
                  description: Audio format (webm, mp3, wav, etc.)
                  default: webm
                responseFormat:
                  type: string
                  description: Response format - 'voice' or 'text'
                  enum: [voice, text]
                  default: voice
                chatId:
                  type: string
                  description: Optional. If not provided, creates a new chat
                title:
                  type: string
                  description: Optional. Title for new chat (defaults to first message)
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  transcript:
                    type: string
                    description: Transcribed user message
                  response:
                    type: string
                    description: AI text response
                  audio:
                    type: string
                    description: Base64-encoded audio response (only if responseFormat is 'voice')
                  sentiment:
                    type: string
                  chatId:
                    type: string
                  responseFormat:
                    type: string
        '400':
          description: Bad request
        '500':
          description: Internal server error
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: ${send_voice_message_invoke_arn}
        passthroughBehavior: when_no_match
        contentHandling: CONVERT_TO_TEXT
    options:
      summary: CORS preflight
      operationId: optionsVoiceChat
      responses:
        '200':
          description: CORS response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: '{"statusCode": 200}'
        responses:
          default:
            statusCode: 200
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization'"

  /chat/{chatId}:
    get:
      summary: Get messages for a specific chat
      operationId: getChatMessages
      security:
        - CognitoAuthorizer: []
      parameters:
        - name: chatId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        text:
                          type: string
                        sender:
                          type: string
                        timestamp:
                          type: string
                        sentiment:
                          type: string
        '500':
          description: Internal server error
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: ${get_chat_invoke_arn}
        passthroughBehavior: when_no_match
        contentHandling: CONVERT_TO_TEXT
    put:
      summary: Update chat title
      operationId: updateChat
      security:
        - CognitoAuthorizer: []
      parameters:
        - name: chatId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  chatId:
                    type: string
                  title:
                    type: string
        '400':
          description: Bad request
        '403':
          description: Forbidden
        '404':
          description: Chat not found
        '500':
          description: Internal server error
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: ${update_chat_invoke_arn}
        passthroughBehavior: when_no_match
        contentHandling: CONVERT_TO_TEXT
    delete:
      summary: Delete a chat
      operationId: deleteChat
      security:
        - CognitoAuthorizer: []
      parameters:
        - name: chatId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  chatId:
                    type: string
        '400':
          description: Bad request
        '403':
          description: Forbidden
        '404':
          description: Chat not found
        '500':
          description: Internal server error
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: ${delete_chat_invoke_arn}
        passthroughBehavior: when_no_match
        contentHandling: CONVERT_TO_TEXT
    options:
      summary: CORS preflight
      operationId: optionsChatById
      responses:
        '200':
          description: CORS response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: '{"statusCode": 200}'
        responses:
          default:
            statusCode: 200
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization'"

components:
  securitySchemes:
    CognitoAuthorizer:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
          - ${user_pool_arn}
